### ISSUE TITLE
Автообновление не работает

### ISSUE THREAD

**Issue by MrJosu** [luzmane/emby.kinopoisk.ru#12]
Плагин включен
В логах от эмби только такаая информация - Value cannot be null. (Parameter 'options.url').  Заново запускал задачу, такой же результат
Версия эмби 4.8.3.0 - работает в докер контейнере
Версию .Net не нашел

**Comment by luzmane** [comment]
логи?

**Comment by MrJosu** [comment]
[kinopoisk.txt](https://github.com/luzmane/emby.kinopoisk.ru/files/14954015/kinopoisk.txt)
Вырезал не связанное с кинопоиском, скажите если нужно больше инфы

**Comment by luzmane** [comment]
это таки баг. постараюсь сегодня\завтра выпустить обновление, и его, к сожаленю, придётся устанавливать вручную.

**Comment by MrJosu** [comment]
> это таки баг. постараюсь сегодня\завтра выпустить обновление, и его, к сожаленю, придётся устанавливать вручную.

Спасибо
Не помрем:) 
А можно как то связаться с Вами? есть маленький личный вопрос по поводу другого плагина

**Comment by luzmane** [comment]
можно на этом [https://emby.media](https://emby.media/community/index.php?) форуме мне послать личное сообщение. мой пользователь там  jelum.

новая версия: [Релиз 1.24.1](https://github.com/luzmane/emby.kinopoisk.ru/releases/tag/v.1.24.1)

**Comment by MrJosu** [comment]
Я запустил автообновление, и он откатился на 1.24.0
[embyserver.txt](https://github.com/luzmane/emby.kinopoisk.ru/files/14960379/embyserver.txt)

**Comment by luzmane** [comment]
Хм, завтра посмотрю. У меня работал как надо

**Comment by MrJosu** [comment]
Если поможет
Сегодня не обновился на 1.24.1
[embykinopoisk.txt](https://github.com/luzmane/emby.kinopoisk.ru/files/14968180/embykinopoisk.txt)

**Comment by luzmane** [comment]
честно говоря, без понятия в чём причина. у меня есть только одна версия - запрос кешируется на 12 часов. попробуйте сейчас (вроде 12 часов уже прошло). но, 1.24.0 - багнутая версия (тема этого тикета), поэтому надо обновить вручную (скачать и положить dll в папку plugins)
