### ISSUE TITLE
Пропадают все коллекции

### ISSUE THREAD

**Issue by azharkov78** [luzmane/emby.kinopoisk.ru#14]
Завис планировщик обновления каналов. Перезапустил сервер, запустил снова планировщик и все категории были удалены :(
В настройках плагина нет выбора Коллекций. Также не дает выбрать другого поставщика.
Было скачено приличное количество трейлеров. Файлы остались, но Коллекция пустая. 
![Снимок экрана 2024-05-06 103411](https://github.com/luzmane/emby.kinopoisk.ru/assets/86604343/f7ccfe5b-6ddb-4521-b73b-b00eb4363880)
[embyserver.txt](https://github.com/luzmane/emby.kinopoisk.ru/files/15217952/embyserver.txt)
![Снимок экрана 2024-05-06 103720](https://github.com/luzmane/emby.kinopoisk.ru/assets/86604343/4c316a9b-e8d5-46a1-ad5f-7353fb9026b9)

**Comment by azharkov78** [comment]
Похоже что проблема kinopoisk.dev. Как бы сделать чтобы не удалялись коллекции?

**Comment by luzmane** [comment]
Сами скачанные файлы не удалились. 
Удаление каналов - это функциональность emby по обновлению каналов

**Comment by luzmane** [comment]
да и нет смысла в этих коллекциях, без поддержки со стороны API ведь даже для получения списка фильмов коллекции плагин посылает дополнительный запрос.
когда API возобновит работу, скачанные файл не будут скачиваться по второму разу (если конечно их не удалили) и обновление интернет канала произойдёт быстрее.

кстати, ключ для apilayer.com перестал быть рабочим. лучше зарегестрировать свой. на сайте можно использовать временную почту (правда не любую, часть они обнаруживают и не дают зарегестрироваться).
