### ISSUE TITLE
Не могу выбрать токен API

### ISSUE THREAD

**Issue by reyist** [luzmane/emby.kinopoisk.ru#15]
Приветствую.
Emby 4.8.6.0 на Ubuntu 22.04.4 LTS LXC container в Proxmox 8.1.11 (Linux version 6.5.11-8-pve (Debian 12.2.0-14))
EmbyKinopoisk v1.25.1
Framework: .NET 6.0.25

В настройках плагина не могу выбрать kinopoiskapiunofficial.tech как вариант выбора API токена. Просто не выбирает данный вариант ни мышью, ни Tab. По дефолту стоит kinopoisk.dev. Пробовал через Firexox, Edge и Chrome - в приватных вкладках и с выключенными плагинами. В старой версии плагина 1.22 все норм. В логах вроде ничего криминального нет.
![2024-05-07_16-36-31](https://github.com/luzmane/emby.kinopoisk.ru/assets/129279441/427661aa-60ab-494d-ace2-50be0efed777)

**Comment by akarpych** [comment]
Таже проблема. Ранее был выбран unofficial, теперь не могу переключиться на другой.

**Comment by luzmane** [comment]
Посмотрю

**Comment by luzmane** [comment]
в этой версии решение: https://github.com/luzmane/emby.kinopoisk.ru/releases/tag/v.1.25.2
