### ISSUE TITLE
Возможность удаления медиатеки "Трейлеры из коллекций Кинопоиска"

### ISSUE THREAD

**Issue by dpovalyaev76** [luzmane/emby.kinopoisk.ru#16]
Данная медиатека появляется сама и не нашел возможности ее отключить (только через удаление плагина)
Хотелось бы галочку в настройках плагина, чтоб этой медиатеки не было... Наша жизнь и так сильно погрязла в "свистелках и звенелках"
Спасибо

P.S. Переустанавливал целиком весь сервер и переехал с 1.6.2 на 1.25.2 сложилось впечатление, что 200 запросов в сутки больше не работают без API-key. Но это не точно.

**Comment by luzmane** [comment]
честно говоря я не знаю как можно её скрыть. спрошу на форуме, а там посмотрим как быть. некоторым пользователям эти каналы нужны 
https://emby.media/community/index.php?/topic/129140-hide-a-channel-media-library/

"200 запросов в сутки". если дефолтный ключ - то это на всех, кто не поставил свой, и этим ключом могут пользоваться не только пользователи плагина, но и просто пользователи API (вытащить его из кода не сложно), так что лучше зарегестрировать свой. если и со своим будут проблемы - в логах плагин должен писать почему пришёл плохой ответ от API. если всё же происходит "какая-то фигня" - смело можно открыть тикет, добавить файл(ы) логов - я посмоторю и постараюсь помочь.

**Comment by dpovalyaev76** [comment]
Спасибо. Твоё знание терминов в Emby натолкнуло меня на:
[(https://emby.media/community/index.php?/topic/50177-hide-a-library-from-home-screen/)]
Все легко убирается через настройки домашнего экрана - тикет можно закрывать

По поводу "200", я получал "Request limit exceeded" после свежей установки сервера и плагина без ключа, перезагрузки и только парочка мелких тестовых сериалов в библиотеке - мне хватало 200, - за неделю вся библиотека обновлялась, спешить некуда... Сделал ключ, потыкал по настройкам и все заработало... У меня нет уверенности что я сразу настроил библиотеку, поэтому не хочу новый Issue делать

**Comment by luzmane** [comment]
@dpovalyaev76 , плагин без ключа (токена) использует ключ по умолчанию, вшитый в плагин. Так что та ситуация, которую я описал выше видимо и произошла - закончились запросы
