### ISSUE TITLE
Does not see the plugin

### ISSUE THREAD

**Issue by MarsBarDesigner** [luzmane/emby.kinopoisk.ru#2]
Вопрос решён!

**Comment by luzmane** [comment]
Какая версия emby?
Какая версия .Net?

**Comment by jiexamedved** [comment]
> Какая версия emby? Какая версия .Net?

А либа получается только под win? Просто у меня Emby в Docker контейнере... Кажется вот он и ответ на вопрос x_x

**Comment by luzmane** [comment]
нет, у меня тоже на докере бегает из "emby/embyserver" образа. какая версия .net в контейнере?

**Comment by jiexamedved** [comment]
> 

Честно. Понятия не имею как её чекнуть из под линя, либо Portainer'a

**Comment by luzmane** [comment]
как создавал\откуда тянул образ?
в Portainer есть опция зайти в образ в терминал. зайдёшь, набери там " dotnet --info"

**Comment by luzmane** [comment]
кстати, добавь сюда логи emby.

**Comment by jiexamedved** [comment]
Ставил отсюда через compose файл: https://hub.docker.com/r/linuxserver/emby 
Образ: [image: lscr.io/linuxserver/emby:latest]

**Comment by jiexamedved** [comment]
> нет, у меня тоже на докере бегает из "emby/embyserver" образа. какая версия .net в контейнере?

.NET 6.0.8

**Comment by jiexamedved** [comment]
[embyserver.txt](https://github.com/luzmane/emby.kinopoisk.ru/files/10573391/embyserver.txt)

**Comment by luzmane** [comment]
Я не знаю почему ты не видишь плагин. По логам он загружается без ошибок:

> 2023-02-02 20:56:20.990 Info App: Loading MusicBrainz, Version=1.0.22.0, Culture=neutral, PublicKeyToken=null from /config/plugins/MusicBrainz.dll
2023-02-02 20:56:20.990 Info App: Loading EmbyKinopoiskRu, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null from /config/plugins/EmbyKinopoiskRu.dll
2023-02-02 20:56:20.990 Info App: Loading Emby.M3UTuner, Version=1.0.13.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Emby.M3UTuner.dll
2

попробуй обновить страницу emby с Ctrl + R (очистить кэш и перезагрузить страницу)

**Comment by MarsBarDesigner** [comment]
> Я не знаю почему ты не видишь плагин. По логам он загружается без ошибок:
> 
> > 2023-02-02 20:56:20.990 Info App: Loading MusicBrainz, Version=1.0.22.0, Culture=neutral, PublicKeyToken=null from /config/plugins/MusicBrainz.dll
> > 2023-02-02 20:56:20.990 Info App: Loading EmbyKinopoiskRu, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null from /config/plugins/EmbyKinopoiskRu.dll
> > 2023-02-02 20:56:20.990 Info App: Loading Emby.M3UTuner, Version=1.0.13.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Emby.M3UTuner.dll
> > 2
> 
> попробуй обновить страницу emby с Ctrl + R (очистить кэш и перезагрузить страницу)

Решилось всё рестартом Emby и Ctrl + R Я скинул последний лог, в первом логе либа не грузилась, но он координально не отличался. За либу спасибо, ищет моментально при правильном форматировании названия файла
