### ISSUE TITLE
Путает фильмы

### ISSUE THREAD

**Issue by sweethome29** [luzmane/emby.kinopoisk.ru#5]
Приветствую! Моя библиотека насчитывает более 3000+ фильмов, у каждого из них название по шаблону "текст (год)" как у самого кинопоиска. Но плагин упорно путает один фильм с другим, например: Джентельмены (2019) на Джентельмены удачи (1972) , Чебурашка (2022) на Чебурашка (1971), Вавилон (2022) на Вавилон 5 (1994). Это только некоторые примеры.. Подскажите, есть варианты это иправить, кроме добавления id в названия ? Не могли бы вы добавить шаблон "текст (год)" , чтобы была привязка к году при поиске?

- плагин 1.8.1

**Comment by luzmane** [comment]
Доброе время суток!
Каким API вы пользуетесь (думаю по умолчанию - kinopoiskapiunofficial.tech)?
Мне нужны логи когда плагин не верно определял фильм.
Версия 1.9.0 должна улучшить поиск для kinopoiskapiunofficial.tech

**Comment by sweethome29** [comment]
Пробовал оба (с удалением всей меты) - остановился на kinopoiskdev. Заметил... Если "замена всех метаданных" то начинается путаница, что у kinopoiskdev , что у kinopoiskapiunofficial.tech .
Но у dev путаницы намного меньше чем tech.
При "поиске отсутствующих" у dev путаницы почти нет, редкие случаи но есть.

Пришлось заново мету собирать, на что хватило токенов) и что бросилось в глаза- прикрепил. 
Плагин 1.9.0 установлен.
[embyserver.txt](https://github.com/luzmane/emby.kinopoisk.ru/files/11106308/embyserver.txt)

**Comment by luzmane** [comment]
Про "Помнить (2015).mkv" - ничего сделать нельзя - два фильма с одинаковыми названиями и в один год.
Про "Загадочное убийство (2020).mkv" - странно, что год уменьшился на 1 - 2020 -> 2019 (не получилось повторить)
Про "Никто (2021).mkv" - добавлю фильтр по имени. Смотри версию 1.9.1
Про "Последствия (2016).mkv" - API не нашёл фильм с годом, пошёл поиск без года и набралось куча левых фильмов. Добавлю фильтр по имени и году (смотри версию 1.9.1)
