### ISSUE TITLE
Не работает на Android

### ISSUE THREAD

**Issue by Sanchous98** [luzmane/emby.kinopoisk.ru#6]
Сервер для Android не отображает плагин в админке. В логах есть ошибки

[embyserver.txt](https://github.com/luzmane/emby.kinopoisk.ru/files/11132307/embyserver.txt)

**Comment by luzmane** [comment]
Причина - версия .Net.
Этот плагин не предполагался для Android. Я могу создать билд, но тест должен провести кто-то другой

**Comment by Sanchous98** [comment]
@luzmane я могу протестировать. На постоянной основе гоняю Emby на Shield TV Pro 2019

**Comment by luzmane** [comment]
ок, я посмотрю что надо, чтоб создать билд для Android и маякну тебе. Оставлю пока issue открытой

**Comment by luzmane** [comment]
посмотри этот билд. по идее должен подняться без проблем. протестируй пожалуйста как обновляет метаданные.
на linux (.net 6) всё ок.
[EmbyKinopoiskRu.dll.zip](https://github.com/luzmane/emby.kinopoisk.ru/files/11136826/EmbyKinopoiskRu.dll.zip)

**Comment by Sanchous98** [comment]
> посмотри этот билд. по идее должен подняться без проблем. протестируй пожалуйста как обновляет метаданные. на linux (.net 6) всё ок. [EmbyKinopoiskRu.dll.zip](https://github.com/luzmane/emby.kinopoisk.ru/files/11136826/EmbyKinopoiskRu.dll.zip)

[embyserver (1).txt](https://github.com/luzmane/emby.kinopoisk.ru/files/11138460/embyserver.1.txt)
Плагин появился, но ничего не находит. Есть ошибки в логах

**Comment by luzmane** [comment]
* остались ли у токена, который ты используешь, разрешённые запросы?
посмотри пожалуйста, не появляется ли у тебя в Alert/Activity в Dashboard какие-нибудь сообщения от плагина.

* попробуй удалить кэш приложения - догадки из-за CoreHttpClientManager.**CacheResponse**.
```
at System.IO.Stream.CopyToAsyncInternal

at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.CacheResponse

at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync
```

**Comment by Sanchous98** [comment]
> * остались ли у токена, который ты используешь, разрешённые запросы?
>   посмотри пожалуйста, не появляется ли у тебя в Alert/Activity в Dashboard какие-нибудь сообщения от плагина.
> * попробуй удалить кэш приложения - догадки из-за CoreHttpClientManager.**CacheResponse**.
> 
> ```
> at System.IO.Stream.CopyToAsyncInternal
> 
> at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.CacheResponse
> 
> at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync
> ```

- Токен исключаю как проблему. Он свежий, тестирую на отдельной медиатеке с одним фильмом
-  Кэш почистил. Проблема осталась. Я посмотрел, что в кэше: там ответ без результатов поиска. Проблема скорее всего в этом, посмотрю в чем ошибка, когда буду у компа

Ответ из кэша:
`{"docs":[],"total":0,"limit":50,"page":1,"pages":0}`

**Comment by Sanchous98** [comment]
@luzmane нашел проблему

Нерабочий запрос:
![Нерабочий запрос](https://user-images.githubusercontent.com/45293316/229555316-119537fb-6888-4534-887e-724db4f07955.png)

Рабочий запрос:
![Рабочий запрос](https://user-images.githubusercontent.com/45293316/229555318-341787bf-6fe1-4393-9d90-d3de94276b26.png)

Разница в том, что нерабочий фильтрует по alternativeName, а рабочий по name. Не знаю в чем смысл alternativeName (документация не описывает этот параметр), но очевидно, что в данном запросе мы фактически пытаемся искать по названию фильма

**Comment by Sanchous98** [comment]
**UPD:** Работает kinopoiskapiunofficial.tech, но не подтянул описание фильма
[embyserver.txt](https://github.com/luzmane/emby.kinopoisk.ru/files/11139926/embyserver.txt)

**Comment by luzmane** [comment]
Он не мог не найти аватар...
Часа через 3 добавлю сюда версию совсем без кеширования http запросов - посмотрим может действительно проблема в этом. Но не хочется - кэш экономит лимит токенов

**Comment by Sanchous98** [comment]
> Он не мог не найти аватар... Часа через 3 добавлю сюда версию совсем без кеширования http запросов - посмотрим может действительно проблема в этом. Но не хочется - кэш экономит лимит токенов

Попробуй в postman-e прогнать этот запрос. У меня Аватара тоже не находит по alternativeName, а по name отлично находит. Имхо, проблема в том, что по какой-то причине в запрос попадает именно alternativeName, а не name, из-за этого в ответ приходит пустой ответ, который не получается распарсить, а не в кэше

**Comment by luzmane** [comment]
AlternativeName - это оригинальное название фильма. Сначала он ищет:
* Имя + год
* Имя
* AlternativeName + год
* AlternativeName.
Вечером ещё посмотрю логи

**Comment by luzmane** [comment]
попробуй эту версию:
[EmbyKinopoiskRu.dll.zip](https://github.com/luzmane/emby.kinopoisk.ru/files/11141612/EmbyKinopoiskRu.dll.zip)

**Comment by luzmane** [comment]
> **UPD:** Работает kinopoiskapiunofficial.tech, но не подтянул описание фильма [embyserver.txt](https://github.com/luzmane/emby.kinopoisk.ru/files/11139926/embyserver.txt)

это баг, сейчас починю

**Comment by Sanchous98** [comment]
> попробуй эту версию: [EmbyKinopoiskRu.dll.zip](https://github.com/luzmane/emby.kinopoisk.ru/files/11141612/EmbyKinopoiskRu.dll.zip)

Теперь работает, но почему-то слоган подтянулся на английском. Но это уже скорее всего кинопоиск, потому что на сайте у них тоже на английском. Сейчас попробую на нормальной медиатеке

**Comment by luzmane** [comment]
супер, тогда выпущу завтра следующий релиз, поддерживающий и Android тоже.
можно закрывать issue, смотри завтра версию 1.11.0
